# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '00 20 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been labeled as stale after 60 days of inactivity.'
        stale-pr-message: 'This pull request has been labeled as stale after 60 days of inactivity.'
        stale-issue-label: 'inactive/stale'
        stale-pr-label: 'inactive/stale'
        days-before-stale: 60
        days-before-close: 30
